//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class welldbEntities : DbContext
    {
        public welldbEntities()
            : base("name=welldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDeedInfo> tblDeedInfoes { get; set; }
        public virtual DbSet<tblLandMan> tblLandMen { get; set; }
    
        public virtual ObjectResult<usp_AssetDumpUnit_Result> usp_AssetDumpUnit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AssetDumpUnit_Result>("usp_AssetDumpUnit");
        }
    
        public virtual ObjectResult<usp_AssetDumpWell_Result> usp_AssetDumpWell()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AssetDumpWell_Result>("usp_AssetDumpWell");
        }
    }
}
