//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeedInfo
    {
        public long ID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> DeedID { get; set; }
        public string UnitName { get; set; }
        public string Play { get; set; }
        public string Company { get; set; }
        public string RightsHeld { get; set; }
        public string DeedName { get; set; }
        public string Grantor { get; set; }
        public string GrantorAddress { get; set; }
        public string GrantorCity { get; set; }
        public string GrantorState { get; set; }
        public string GrantorZip { get; set; }
        public string OwnerNumber { get; set; }
        public string TractCity { get; set; }
        public Nullable<System.DateTime> InstrumentDate1 { get; set; }
        public string InstrumentNumber1 { get; set; }
        public string Book1 { get; set; }
        public Nullable<System.DateTime> InstrumentDate2 { get; set; }
        public string InstrumentNumber2 { get; set; }
        public string Book2 { get; set; }
        public string PledgedBank { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> LeaseTerm { get; set; }
        public string TermUnit { get; set; }
        public Nullable<System.DateTime> LeaseExpires { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public string Referral { get; set; }
        public string CheckNumber { get; set; }
        public string Tract { get; set; }
        public string TractStatus { get; set; }
        public string CountAcres { get; set; }
        public Nullable<decimal> Royalty { get; set; }
        public Nullable<decimal> ORRIBurden { get; set; }
        public Nullable<decimal> GNRI { get; set; }
        public Nullable<decimal> TotalDeedGrossAcres { get; set; }
        public Nullable<decimal> TotalDeedNetAcres { get; set; }
        public Nullable<decimal> TotalDeedCoAcres { get; set; }
        public Nullable<decimal> TractGrossAcres { get; set; }
        public Nullable<decimal> TractSurfaceAcres { get; set; }
        public Nullable<decimal> TractNetAcres { get; set; }
        public Nullable<decimal> TractCoAcres { get; set; }
        public Nullable<decimal> GrantorTractInt { get; set; }
        public Nullable<decimal> CoTractInt { get; set; }
        public string Lot { get; set; }
        public string Block { get; set; }
        public string Addition { get; set; }
        public string DeedLegal { get; set; }
        public string TractLegal { get; set; }
        public Nullable<System.DateTime> Emailed { get; set; }
        public string PayStatus { get; set; }
        public string TractDropReason { get; set; }
        public Nullable<System.DateTime> TractDropDate { get; set; }
        public Nullable<decimal> CalculatedUnitInt { get; set; }
        public string FileLoc { get; set; }
        public string DeedType { get; set; }
        public string DeedForm { get; set; }
        public string Provisions { get; set; }
        public string ProvisionRemarks { get; set; }
        public Nullable<System.DateTime> NextObDate { get; set; }
        public string Mortgagee { get; set; }
        public string SubordStatus { get; set; }
        public Nullable<System.DateTime> SentToBank { get; set; }
        public Nullable<System.DateTime> SentToOperator { get; set; }
        public Nullable<System.DateTime> RcvdCol { get; set; }
        public string SubordRecording { get; set; }
        public string SubordType { get; set; }
        public Nullable<System.DateTime> SetupDate { get; set; }
        public string DPULease { get; set; }
        public string DOLease { get; set; }
        public string P12TractNumber { get; set; }
        public string Abstract { get; set; }
        public string Survey { get; set; }
        public string TractName { get; set; }
        public string Lessee { get; set; }
        public string ContractNumber { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string DeedFile { get; set; }
        public string TitleFile { get; set; }
    }
}
